version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .  # Asegúrate de que esto sea un objeto (mapping)
    container_name: nest_app
    restart: always
    depends_on:  # Asegúrate de que esto sea una lista (array)
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydb?schema=public"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]

volumes:
  pgdata: